const SUPABASE_URL='https://dpiwdhtbhwjgatvcfkcb.supabase.co';const SUPABASE_KEY='sb_publishable_PSZnTEo74jObih_6TTpXVQ_tJwzTnXY';const sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);const $=id=>document.getElementById(id);let users=[],branches=[];
function message(text,ok=false){$('message').textContent=text;$('message').className='message'+(ok?' ok':'');$('message').hidden=!text}
function cardLogin(){ $('authContent').innerHTML=`<h1>Welcome back</h1><p>Sign in to manage the staff accounts that can access Safar Link.</p><form class="form" id="loginForm"><label>Email<input id="email" type="email" required autocomplete="username" placeholder="admin@company.com"></label><label>Password<input id="password" type="password" required autocomplete="current-password" placeholder="Your password"></label><button class="primary" type="submit">Sign in</button></form>`;bindLogin()}
function cardSignup(){ $('authContent').innerHTML=`<h1>Create your admin</h1><p>This setup is available only once. The first account becomes the primary Safar Link administrator. After it is created, this sign-up card disappears permanently.</p><form class="form" id="signupForm"><label>Full name<input id="fullName" required autocomplete="name" placeholder="Your name"></label><label>Email<input id="email" type="email" required autocomplete="email" placeholder="admin@company.com"></label><label>Password<input id="password" type="password" minlength="8" required autocomplete="new-password" placeholder="At least 8 characters"></label><button class="primary" type="submit">Create admin account</button></form>`;bindSignup()}
async function getStatus(){try{const r=await fetch(`${SUPABASE_URL}/functions/v1/safar-admin-users`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'status'})});return await r.json()}catch{return null}}
function bindSignup(){$('signupForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;message('Creating your secure admin account…');try{const r=await fetch(`${SUPABASE_URL}/functions/v1/safar-admin-users`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'bootstrap',full_name:$('fullName').value.trim(),email:$('email').value.trim(),password:$('password').value})}).then(x=>x.json());if(r.error)throw Error(r.error);cardLogin();message('Admin created. Sign in with the account you just created.',true)}catch(e){message(e.message||'Could not create the admin account.')}finally{btn.disabled=false}}}
function bindLogin(){$('loginForm').onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;message('Signing you in…');try{const {data,error}=await sb.auth.signInWithPassword({email:$('email').value.trim(),password:$('password').value});if(error)throw error;const {data:a}=await sb.from('safar_admins').select('id,full_name').eq('id',data.user.id).maybeSingle();const {data:p}=await sb.from('profiles').select('id,role,active').eq('id',data.user.id).maybeSingle();if(!a||!p||p.role!=='admin'||p.active!==true){await sb.auth.signOut();throw Error('This account is not an active SF Admin administrator.')}message('');await showDashboard()}catch(e){message(e.message||'Sign in failed.')}finally{btn.disabled=false}}}
async function showDashboard(){ $('authScreen').classList.add('logged-in');$('authScreen').hidden=true;$('dashboard').hidden=false;await load() }
async function load(){const [p,b]=await Promise.all([sb.from('profiles').select('id,full_name,phone,role,active,branch_id,branches(name,city)').in('role',['staff','admin']).order('created_at',{ascending:false}),sb.from('branches').select('*').order('city')]);if(p.error)return message(p.error.message);users=p.data||[];branches=b.data||[];$('count').textContent=users.length;$('active').textContent=users.filter(x=>x.active).length;$('branches').textContent=branches.length;$('branch').innerHTML=branches.map(b=>`<option value="${b.id}">${esc(b.city)} — ${esc(b.name)}</option>`).join('');render()}
function render(){const q=($('search').value||'').toLowerCase();const list=users.filter(u=>[u.full_name,u.phone,u.role,u.branches?.city].some(v=>String(v||'').toLowerCase().includes(q)));$('users').innerHTML=list.length?list.map(u=>`<tr><td><strong>${esc(u.full_name||'Unnamed')}</strong></td><td>${esc(u.role)}</td><td>${esc(u.branches?.name||'Unassigned')}</td><td>${esc(u.phone||'—')}</td><td><span class="pill ${u.active?'':'off'}">${u.active?'Active':'Disabled'}</span></td><td>${u.role!=='admin'&&u.active?`<button class="secondary" data-disable="${u.id}">Disable</button>`:''}</td></tr>`).join(''):'<tr><td colspan="6">No accounts found.</td></tr>';document.querySelectorAll('[data-disable]').forEach(b=>b.onclick=()=>disableUser(b.dataset.disable))}
const esc=v=>String(v??'').replace(/[&<>\'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
async function api(action,body){const {data:{session}}=await sb.auth.getSession();if(!session)return {error:'Your session expired. Please sign in again.'};return fetch(`${SUPABASE_URL}/functions/v1/safar-admin-users`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({action,...body})}).then(r=>r.json())}
async function disableUser(id){if(!confirm('Disable this staff account?'))return;const r=await api('disable_user',{user_id:id});if(r.error)return message(r.error);await load();message('Staff account disabled.',true)}function openModal(){$('userModal').hidden=false}function closeModal(){$('userModal').hidden=true}
$('newUser').onclick=openModal;$('close').onclick=closeModal;$('userModal').onclick=e=>{if(e.target===$('userModal'))closeModal()};$('search').oninput=render;$('logout').onclick=async()=>{await sb.auth.signOut();$('dashboard').hidden=true;$('authScreen').hidden=false;$('authScreen').classList.remove('logged-in');cardLogin();message('Signed out.',true)};$('userForm').onsubmit=async e=>{e.preventDefault();const r=await api('create_user',{full_name:$('fullName').value.trim(),email:$('userEmail').value.trim(),phone:$('phone').value.trim(),branch_id:$('branch').value,password:$('userPassword').value});if(r.error)return message(r.error);closeModal();e.target.reset();await load();message('Staff account created.',true)};
(async()=>{const {data:{session}}=await sb.auth.getSession();if(session){const {data:a}=await sb.from('safar_admins').select('id,full_name').eq('id',session.user.id).maybeSingle();const {data:p}=await sb.from('profiles').select('id,role,active').eq('id',session.user.id).maybeSingle();if(a&&p?.role==='admin'&&p.active===true)return showDashboard();await sb.auth.signOut()}const status=await getStatus();if(status?.hasAdmin)cardLogin();else cardSignup()})();