import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.57.0";
const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, content-type","Access-Control-Allow-Methods":"POST, OPTIONS","Content-Type":"application/json"};
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:cors});
const url=Deno.env.get("SUPABASE_URL")!;const service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;const db=createClient(url,service,{auth:{autoRefreshToken:false,persistSession:false}});
async function adminActor(req:Request){const token=(req.headers.get("authorization")||"").replace(/^Bearer\s+/i,"");if(!token)return null;const {data,error}=await db.auth.getUser(token);if(error||!data.user)return null;const {data:p}=await db.from("profiles").select("id,role,active").eq("id",data.user.id).maybeSingle();return p?.active&&p.role==='admin'?data.user:null;}
Deno.serve(async req=>{if(req.method==='OPTIONS')return new Response('ok',{headers:cors});if(req.method!=='POST')return json({error:'Method not allowed.'},405);const actor=await adminActor(req);if(!actor)return json({error:'Administrator authorization required.'},403);let b:any;try{b=await req.json()}catch{return json({error:'Invalid JSON.'},400)};
if(b.action==='list_users'){const [{data:profiles,error:pe},{data:branches,error:be}]=await Promise.all([db.from('profiles').select('id,full_name,phone,role,active,branch_id,created_at').in('role',['staff','admin']).order('created_at',{ascending:false}),db.from('branches').select('id,name,city,active').order('city')]);if(pe||be)return json({error:(pe||be)?.message||'Could not load accounts.'},500);const users=[];for(const p of profiles||[]){const {data:u,error:e}=await db.auth.admin.getUserById(p.id);if(e)return json({error:e.message},500);users.push({...p,email:u.user?.email||'',branches:(branches||[]).find(x=>x.id===p.branch_id)||null});}return json({users,branches:branches||[]});}
if(b.action==='create_user'){const email=String(b.email||'').trim().toLowerCase(),password=String(b.password||''),full_name=String(b.full_name||'').trim(),branch_id=String(b.branch_id||'').trim();if(!email||password.length<8||!full_name||!branch_id)return json({error:'Name, email, password and terminal are required.'},400);const {data:branch}=await db.from('branches').select('id').eq('id',branch_id).maybeSingle();if(!branch)return json({error:'Selected terminal does not exist.'},400);const {data:u,error:ue}=await db.auth.admin.createUser({email,password,email_confirm:true});if(ue||!u.user)return json({error:ue?.message||'Could not create account.'},400);const {error:pe}=await db.from('profiles').insert({id:u.user.id,full_name,phone:String(b.phone||'').trim()||null,role:'staff',active:true,branch_id});if(pe){await db.auth.admin.deleteUser(u.user.id);return json({error:pe.message},400)}return json({ok:true,id:u.user.id});}
if(b.action==='update_user'){const id=String(b.user_id||'').trim(),full_name=String(b.full_name||'').trim(),email=String(b.email||'').trim().toLowerCase(),password=String(b.password||'');if(!id||!full_name||!email)return json({error:'User id, name and email are required.'},400);const {data:p}=await db.from('profiles').select('id,role').eq('id',id).maybeSingle();if(!p||p.role!=='staff')return json({error:'Only staff accounts can be edited here.'},400);if(password&&password.length<8)return json({error:'Password must be at least 8 characters.'},400);const {error:ae}=await db.auth.admin.updateUserById(id,{email,password:password||undefined});if(ae)return json({error:ae.message},400);const {error:pe}=await db.from('profiles').update({full_name,updated_at:new Date().toISOString()}).eq('id',id).eq('role','staff');if(pe)return json({error:pe.message},400);return json({ok:true});}
if(b.action==='disable_user'){const id=String(b.user_id||'').trim();const {data:p}=await db.from('profiles').select('id,role').eq('id',id).maybeSingle();if(!p||p.role!=='staff')return json({error:'Only staff accounts can be disabled here.'},400);const {error:pe}=await db.from('profiles').update({active:false,updated_at:new Date().toISOString()}).eq('id',id).eq('role','staff');if(pe)return json({error:pe.message},400);const {error:ae}=await db.auth.admin.updateUserById(id,{ban_duration:'876000h'});if(ae)return json({error:ae.message},400);return json({ok:true});}
return json({error:'Unknown action.'},400);});